### ISSUE TITLE
es folder is not included in npm bundle

### ISSUE THREAD

**Issue by petrjaros** [enniel/graphql-geojson-scalar-types#5]
https://github.com/enniel/graphql-geojson-scalar-types/blob/a1b24bed384ac989f76fb9756d55662bdd0e725b/package.json#L7

entries `module` and `jsnext:main` in `package.json` point to non existing files. Please either remove these lines or include `es` folder into npm package.

And thanks for great package !

**Comment by enniel** [comment]
fixed in version 0.1.0
